spring:
  application:
    name: Bookiero
  jpa:
    open-in-view: false
  profiles:
    active: ${SPRING_PROFILE:develop}
  datasource:
    url: ${DATABASE_URL}/bookiero
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

springdoc:
  swagger-ui:
    path: /api/docs
