name: Automated Tests

on:
  pull_request:
    types:
      - opened
    branches:
      - main

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Check commit count
        run: rev-list --full-history --all | wc -l

      - name: Set up JDK 21 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          architecture: x64

      - name: Run Tests (Maven)
        run: ./mvnw clean test
